name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_SECRET }}
        github-token: ${{ secrets.GH_TOKEN }}
        vercel-org-id: team_DHzfJC6nHBOMT2ToWx7fb884
        vercel-project-id: prj_dsi8KqUijxrmxJycZgM0035K2FaU
        vercel-project-name: tomytex-new
        working-directory: ./
